# Generated by Django 5.2.3 on 2025-06-25 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_books_available_copies_books_isbn_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_author_name', models.CharField(max_length=100)),
                ('c_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.books')),
                ('c_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.member')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('c_member', 'c_book'), name='unique_person_group')],
            },
        ),
    ]
