# Generated by Django 5.2.3 on 2025-06-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cart'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_person_group',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='c_author_name',
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('c_member', 'c_book'), name='unique_person_book'),
        ),
    ]
