# Generated by Django 5.2.3 on 2025-06-26 07:47

import django.core.validators
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_cart_unique_person_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10), home.models.validate_gmail]),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='pass', help_text='Minimum 8 characters. For better security, store hashed passwords.', max_length=128, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
    ]
