# Generated by Django 5.2.3 on 2025-06-26 22:18

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_member_email_member_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='author_name',
        ),
        migrations.AlterField(
            model_name='issue',
            name='due_date',
            field=models.DateField(default=home.models.get_due_date),
        ),
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(to='home.author'),
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.publisher'),
        ),
    ]
