# Generated by Django 5.2.3 on 2025-06-26 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_author_publisher_remove_books_author_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='authors',
            new_name='author_name',
        ),
    ]
